name: LeetCode CI Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t leetcode-ci .

      - name: Run tests inside Docker
        run: docker run --rm leetcode-ci

      - name: Run linting (flake8)
        run: docker run --rm leetcode-ci flake8 problems tests

      - name: Check code formatting (black)
        run: docker run --rm leetcode-ci black --check problems tests
